### ISSUE TITLE
Circuit "Configuration" Data

### ISSUE THREAD

**Issue by dan-fritchman** [BWRC-AMS-ML-Discovery/AutoCkt#4]
There's one project-level YAML-format configuration file, which looks like so:

```yaml
database_dir: "Autockt/checkpoint/db/two_stage_opamp_ngspice"
dsn_netlist: "eval_engines/ngspice/ngspice_inputs/netlist/two_stage_opamp.cir"
num_process: 1

params:
  mp1:  !!python/tuple [1, 100, 1]
  mn1:  !!python/tuple [1, 100, 1]
  mp3:  !!python/tuple [1, 100, 1]
  mn3:  !!python/tuple [1, 100, 1]
  mn4:  !!python/tuple [1, 100, 1]
  mn5:  !!python/tuple [1, 100, 1]
  cc:   !!python/tuple [!!float 0.1e-12, !!float 10.0e-12, !!float 0.1e-12]

#Every specification output will be normlaized in the order of (gain, ibias, pm, ugbw)
normalize: !!python/tuple [350, 0.001, 60, 950000.0]

#during training, at reset a specification will be chosen at random between [min,max,#]
target_specs:
  gain_min: !!python/tuple [200,400]
  ugbw_min: !!python/tuple [!!float 1.0e6, !!float 2.5e7]
  phm_min: !!python/tuple [60,60.0000001]
  ibias_max: !!python/tuple [0.0001, 0.01]
```

So:

* That has 17 non-empty, non-comment lines.
* Of them, 13 require the !!python modifier.

In other words: that ain't YAML, it's just Python code with worse syntax.  
Just make it code.

We should add: the Python language has some helpful features which were not available when (some of) AutoCkt was written. The dataclasses added in Python 3.7 are particularly helpful for something like this. (They'd probably be an equal number of lines-of-code, and probably fewer characters on those lines.)
